/** Portable entry point for the research demo, including its checked-in world. */
import { cpSync, existsSync, mkdirSync, readFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { createRequire } from 'node:module'
import { spawnSync } from 'node:child_process'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
process.chdir(root)
const mode = process.argv[2] ?? 'prepare'
if (!['prepare', 'dev', 'build'].includes(mode)) throw new Error(`Unknown mode: ${mode}`)
const maps = resolve(process.env.ALWAYS_ON_MAPS_DIR || join(root, '../game/maps'))
for (const [name, target] of [
  ['ntu-campus-v3', join(root, 'game-assets/maps/ntu-campus-v3')],
  ['ntu-campus-v2', join(root, 'assets/maps/ntu')]
]) {
  const source = join(maps, name)
  if (existsSync(join(source, 'index.json'))) {
    mkdirSync(dirname(target), { recursive: true })
    cpSync(source, target, { recursive: true })
  }
  if (!existsSync(join(target, 'index.json'))) {
    throw new Error(`Missing ${name}. Clone the whole website repository, or set ALWAYS_ON_MAPS_DIR to its game/maps directory.`)
  }
  const index = JSON.parse(readFileSync(join(target, 'index.json'), 'utf8'))
  for (const region of Object.keys(index.region ?? {})) {
    if (!existsSync(join(target, 'region', region))) throw new Error(`Missing map region: ${name}/${region}`)
  }
}
console.log('Campus assets ready. The ECCV world is generated by src/eccvWorld.ts.')
if (mode !== 'prepare') {
  const require = createRequire(import.meta.url)
  const cli = join(dirname(require.resolve('@rsbuild/core/package.json')), 'bin/rsbuild.js')
  const result = spawnSync(process.execPath, [cli, mode, ...process.argv.slice(3)], {
    stdio: 'inherit',
    env: { ...process.env, DISABLE_SERVICE_WORKER: 'true', CONFIG_JSON_SOURCE: 'BUNDLED',
      LOCAL_CONFIG_FILE: 'config.always-on.json', GITHUB_REPOSITORY: 'Always-On-Agent/Always-On-Agent.github.io' }
  })
  if (result.error) throw result.error
  process.exitCode = result.status ?? 1
}
